version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: daily
      time: '08:00'
      timezone: Europe/Amsterdam

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
      time: '08:00'
      timezone: Europe/Amsterdam
