# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: Install dependencies, start dev server
    init: >
      nvm install 16 &&
      nvm use 16 &&
      make

    command: mkdocs serve

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 8000
    onOpen: open-browser
    visibility: private
