module.exports = {
  docs: [
    {
      type: "category",
      label: "About this guide",
      items: [
        "about_this_guide/project_license",
        "about_this_guide/guide_introduction",
      ],
    },
    {
      type: "category",
      label: "Git basics",
      items: ["git_basics/introduction_to_git"],
    },
    {
      type: "category",
      label: "Getting started",
      items: [
        "getting_started/conventions",
        "getting_started/list_of_abbreviations",
        "getting_started/installing_git",
        "getting_started/create_a_github_account",
        "getting_started/configuring_git",
        "getting_started/getting_help_with_git",
      ],
    },
    {
      type: "category",
      label: "The Nano text editor",
      items: ["the_nano_text_editor/introduction_to_the_nano_text_editor"],
    },
    {
      type: "category",
      label: "Git sandbox",
      items: [
        "git_sandbox/setup_your_git_sandbox",
        "git_sandbox/shell_expansion",
        "git_sandbox/explore_your_git_sandbox",
        "git_sandbox/introduction_to_git_status",
        "git_sandbox/create_a_new_file_and_track_it",
        "git_sandbox/making_your_first_commit",
        "git_sandbox/add_extra_lines_to_file",
        "git_sandbox/use_git_restore_to_undo_things",
        `git_sandbox/create_a_new_branch`,
        "git_sandbox/switching_between_branches",
        "git_sandbox/your_first_merge",
        "git_sandbox/create_your_first_github_repo",
        "git_sandbox/editing_a_file_on_github",
        "git_sandbox/merge_pull_request",
        "git_sandbox/fetching_changes_merging_git_pull",
        "git_sandbox/check_the_repository_history_with_git_log",
      ],
    },
    {
      type: "category",
      label: "Best practices",
      items: [
        "best_practices/use_a_gitignore_file",
        "best_practices/split_up_your_commits",
        "best_practices/write_good_commit_messages",
        "best_practices/git_aliases",
        `best_practices/use_a_linter`,
        "best_practices/dealing_with_merges",
        "best_practices/use_a_dependency_bot",
        "best_practices/testing_and_github_actions",
      ],
    },
    {
      type: "category",
      label: "Advanced topics",
      items: [
        "advanced_topics/working_with_large_files",
        "advanced_topics/advanced_git_configuration",
        "advanced_topics/contribute_to_a_project_by_forking",
        "advanced_topics/clean_up_your_git_history",
        "advanced_topics/use_git_bisect_to_find_bugs",
        "advanced_topics/github_cli",
      ],
    },
    {
      type: "category",
      label: "Further resources",
      items: ["further_resources/recommended_reading"],
    },
  ],
};
