name: Bug Report
description: Report a bug
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill out this bug report!

  - type: textarea
    id: describe-the-bug
    attributes:
      label: Describe the bug
      description: Tell us what's going wrong.
    validations:
      required: true

  - type: textarea
    id: give-the-steps-to-reproduce
    attributes:
      label: Give the steps needed to reproduce the behavior.
      description: Provide a ordered list with steps to reproduce.
      value: |
        1.
        2.
        3.
        ...
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: What did you expect to happen?
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: dropdown
    id: have-you-thought-of-a-possible-solution
    attributes:
      label: Have you thought of a possible solution?
      options:
        - "Yes"
        - "No"
    validations:
      required: true

  - type: textarea
    id: possible-solution-suggestion
    attributes:
      label: If you have thought of a solution, please tell us about it!
      description: Explain the possible solution.

  - type: dropdown
    id: do-you-want-to-help-fix-the-bug
    attributes:
      label: Do you want to help fix the bug?
      options:
        - "Yes"
        - "Maybe"
        - "No"
    validations:
      required: true

  - type: textarea
    id: is-there-anything-else-we-need-to-know
    attributes:
      label: Is there anything else we need to know?
