# This workflow uses npm to install Yarn.
# After Yarn is installed, it will use Yarn to install the dependencies and create a build.
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2.1.2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Yarn with npm
      run: npm install -g yarn

    - name: Use Yarn to install dependencies and create a build
      run: |
        yarn install
        yarn build
